### ISSUE TITLE
Unexpected Behavior When Using "Recover a VOD"

### ISSUE THREAD

**Issue by suit7** [PaaaulZ/TwitchRecover#11]
a streamscharts link would yield a link for a "hidden" vod stored in the servers as (vods-secure.twitch.tv/) but that changed as the program would crash yielding: 

Exception in thread "main" java.lang.NullPointerException
 at TwitchRecover. Core. Compute.get UNIX(Compute.java:48)
 at TwitchRecover. Core.Retrieval.retrieved(Retrieval.java:25)
 at TwitchRecover. Core.VOD.retrieved(VOD.java:72)
 at TwitchRecover.CLI. Handlers.VODHandler.recover(VODHandler.java:95)
 at TwitchRecover.CLI. Handlers.VODHandler.(VODHandler.java:24)
 at TwitchRecover.CLI.Chandler.main(Chandler.java:24)
 at TwitchRecover.CLI.CLI.main(CLI.java:13)

in this example: (https://streamscharts.com/channels/xqcow/streams/39675722617) a vod stored in the cloudfront should yield this message:
<img width="216" alt="no vod available" src="https://user-images.githubusercontent.com/104237793/164838456-23314aed-d933-47f4-8b84-1879305c977b.PNG">
 but instead the following message popsup 
<img width="598" alt="4-22-21" src="https://user-images.githubusercontent.com/104237793/164838182-75c221b9-9495-4a17-b6d8-f4ff66c987d0.PNG">

It's worth noting that this behavior didn't occur till 4-22

**Comment by PaaaulZ** [comment]
StreamsCharts added CloudFlare as a protection against automated scripts like this so it's currently broken until I find another way. Please use the other provider, enter information manually or wait until I find a fix.

Thank you
