### ISSUE TITLE
Program not working for me.

### ISSUE THREAD

**Issue by Kaastiron** [PaaaulZ/TwitchRecover#6]
hey i've been using the original twitch recover with no issue but wanted to use this fork to be able to the streamscharts links but I just can't seem to get it to work.

I get this error when trying to get a link to a VOD (1st option) 
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at TwitchRecover.Core.API.VideoAPI.getSubVODFeeds(VideoAPI.java:80)
at TwitchRecover.Core.VOD.getVODFeeds(VOD.java:113)
at TwitchRecover.CLI.Handlers.VODHandler.retrieve(VODHandler.java:38)
at TwitchRecover.CLI.Handlers.VODHandler.(VODHandler.java:18)
at TwitchRecover.CLI.CLIHandler.main(CLIHandler.java:24)
at TwitchRecover.CLI.CLI.main(CLI.java:13)

And I can't seem to recover any VODS using it, it will always tell me 
NO RESULTS FOUND.
The VOD cannot be found on Twitch servers.
even when i'm able to recover the VOD with the original program.

I've downloaded the latest java and I have JDK 18 and I set the path in enviroment variables. I am a comeplete amatuer so I may be missing something else but I'm at a loss currently.

**Comment by PaaaulZ** [comment]
Fixed in releave v.1.0.2-beta
